"""codeai: a durable epistemic runtime for AI collaboration."""

from .adapters import (
    ActionRequest,
    ActionResult,
    ActionStatus,
    CallResult,
    CallSpec,
    CheckRequest,
    CheckResult,
    CheckVerdict,
    CognitionAdapter,
    ExecutionAdapter,
    FakeCognitionAdapter,
    VerificationAdapter,
)
from .analysis import build_report, export_experiment, render_report
from .artifacts import ArtifactCorruptionError, FileArtifactStore
from .claims import disagreement_report, project_claims, project_relationships
from .context import (
    CompilationTrace,
    ContextBudgetUnsatisfiable,
    ContextCandidate,
    ContextCompiler,
    ContextSealViolation,
    RequiredContextMissing,
    TraceEntry,
)
from .corpus import CORPUS_VERSION, CorpusTask, seeded_corpus, visible_prompt
from .domain import (
    ActorRef,
    ArtifactRef,
    Authority,
    Budget,
    Claim,
    ClaimRelationship,
    ClaimRelationshipType,
    ClaimStatus,
    ContextPackage,
    Decision,
    Directive,
    EvidenceClass,
    Seal,
    Task,
    Variant,
)
from .domain import (
    CallSpec as CallSpecAlias,
)
from .experiments import (
    ArmDef,
    ExperimentBudget,
    ExperimentConfig,
    build_config,
    create_experiment,
    get_experiment,
    plan_experiment,
    run_arm,
)
from .ledger import ArtifactRecord, Event, SQLiteLedger
from .modelconfig import ModelConfig, ModelMapping, load_model_config
from .providers import (
    AnthropicAdapter,
    MissingCredentialsError,
    OpenAIAdapter,
    OpenAICompatibleAdapter,
    ProviderError,
)
from .runtime import PreconditionMismatch, Runtime, default_repository_state_hash
from .scheduler import Operation, SchedulerDecision, SchedulerInput, decide_next_step
from .verifier import LocalCommandVerifier

__all__ = [
    "CORPUS_VERSION",
    "ActionRequest",
    "ActionResult",
    "ActionStatus",
    "ActorRef",
    "AnthropicAdapter",
    "ArmDef",
    "ArtifactCorruptionError",
    "ArtifactRecord",
    "ArtifactRef",
    "Authority",
    "Budget",
    "CallResult",
    "CallSpec",
    "CallSpecAlias",
    "CheckRequest",
    "CheckResult",
    "CheckVerdict",
    "Claim",
    "ClaimRelationship",
    "ClaimRelationshipType",
    "ClaimStatus",
    "CognitionAdapter",
    "CompilationTrace",
    "ContextBudgetUnsatisfiable",
    "ContextCandidate",
    "ContextCompiler",
    "ContextPackage",
    "ContextSealViolation",
    "CorpusTask",
    "Decision",
    "Directive",
    "Event",
    "EvidenceClass",
    "ExecutionAdapter",
    "ExperimentBudget",
    "ExperimentConfig",
    "FakeCognitionAdapter",
    "FileArtifactStore",
    "LocalCommandVerifier",
    "MissingCredentialsError",
    "ModelConfig",
    "ModelMapping",
    "OpenAIAdapter",
    "OpenAICompatibleAdapter",
    "Operation",
    "PreconditionMismatch",
    "ProviderError",
    "RequiredContextMissing",
    "Runtime",
    "SQLiteLedger",
    "SchedulerDecision",
    "SchedulerInput",
    "Seal",
    "Task",
    "TraceEntry",
    "Variant",
    "VerificationAdapter",
    "build_config",
    "build_report",
    "create_experiment",
    "decide_next_step",
    "default_repository_state_hash",
    "disagreement_report",
    "export_experiment",
    "get_experiment",
    "load_model_config",
    "plan_experiment",
    "project_claims",
    "project_relationships",
    "render_report",
    "run_arm",
    "seeded_corpus",
    "visible_prompt",
]
